name: Github Actions
on: [push, pull_request]
jobs:
  build:
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        nim-version: ['2.2.10', 'stable']

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: jiro4989/setup-nim-action@v2
      with:
        nim-version: ${{ matrix.nim-version }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install Atlas
      run: curl -fsSL https://raw.githubusercontent.com/nim-lang/atlas/HEAD/install.sh | bash -

    - name: Versions
      run: |
        nim -v
        atlas -v

    - name: Cache packages
      uses: actions/cache@v4
      with:
        path: deps/
        key: ${{ runner.os }}-nim-${{ matrix.nim-version }}-atlas-${{ hashFiles('mummy.nimble') }}

    - name: Install dependencies
      run: atlas install -t:8 --features:testing

    - run: nim c -r -d:useMalloc tests/test.nim
    - run: nim c -r -d:useMalloc tests/test_http.nim
    - run: nim c --mm:atomicArc -r -d:useMalloc tests/test_http.nim
      if: ${{ matrix.atomic_arc }}
    - run: nim c -r -d:useMalloc tests/test_http2.nim
    - run: nim c -r -d:useMalloc tests/test_multi_bind.nim
    - run: nim c -r -d:useMalloc tests/test_websockets.nim
    - run: nim c -r -d:useMalloc -d:mummyNoWorkers tests/fuzz_recv.nim
