name: docs

on:
  push:
    branches:
    - master
  pull_request:

permissions:
  contents: write

env:
  NIM_VERSION: '2.2.10'
  NIM_SRC: src/mummy.nim
  DEPLOY_DIR: .gh-pages

jobs:
  docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v4

    - uses: jiro4989/setup-nim-action@v2
      with:
        nim-version: ${{ env.NIM_VERSION }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install Atlas
      run: curl -fsSL https://raw.githubusercontent.com/nim-lang/atlas/HEAD/install.sh | bash -

    - name: Cache packages
      uses: actions/cache@v4
      with:
        path: deps/
        key: docs-${{ runner.os }}-nim-${{ env.NIM_VERSION }}-atlas-${{ hashFiles('mummy.nimble') }}

    - name: Install dependencies
      run: atlas install -t:8

    - name: Generate router documentation
      run: >-
        nim doc --index:on
        --git.url:https://github.com/${{ github.repository }}
        --git.commit:master
        --out:${{ env.DEPLOY_DIR }}/
        src/mummy/routers.nim

    - name: Generate project documentation
      run: >-
        nim doc --index:on --project
        --git.url:https://github.com/${{ github.repository }}
        --git.commit:master
        --out:${{ env.DEPLOY_DIR }}
        ${{ env.NIM_SRC }}

    - name: Build documentation index
      run: nim buildIndex -o:${{ env.DEPLOY_DIR }}/index.html ${{ env.DEPLOY_DIR }}

    - name: Deploy documentation
      if: github.event_name == 'push'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ env.DEPLOY_DIR }}
